// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteJWT.Models;

namespace TesteJWT.Migrations
{
    [DbContext(typeof(TesteJWTDBContext))]
    [Migration("20211004193151_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TesteJWT.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Usuario")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(60)")
                        .HasColumnName("CD_Email");

                    b.Property<string>("Nome")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("NM_Usuario");

                    b.Property<string>("Perfil")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("CD_Perfil_");

                    b.Property<string>("Senha")
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("CD_Senha");

                    b.HasKey("Id");

                    b.ToTable("TblUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
